version: "3.7"

services:
  backend:
    container_name: spring-boot
    build:
      context: ./backend
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"
    depends_on:
      - database
    networks:
      - quickplate_network

  database:
    container_name: postgres-database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - quickplate_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
      - "3010:3010"
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - quickplate_network

networks:
  quickplate_network:
    driver: bridge